### ISSUE TITLE
search_graph : unable to display chinese or other non ASCII character

### ISSUE THREAD

**Issue by lkfo415579** [EdinburghNLP/nematus#54]
I have been trying set different UTF8 encoding setting, it still not working in your hypgraph.py program.

I wrote a single pygraphviz python program for testing the chinese display problem, it works. 

![sg](https://user-images.githubusercontent.com/10741881/29347007-e74ca36e-827b-11e7-9a7c-3d93b8bcdf1e.png)

**Comment by laeubli** [comment]
Hi @lkfo415579,

Thanks for your report. I've been looking into this, and the problem here seems to be that UTF-8 characters in `record`-shaped nodes aren't rendered correctly by Graphviz's `dot` program. If you disable the `detailed` option in translate.py (currently: [line 550](https://github.com/EdinburghNLP/nematus/blob/master/nematus/translate.py#L550)), normal shapes are used and non-ASCII characters are rendered correctly with the current code:

<img src="https://user-images.githubusercontent.com/4609749/29409743-f6e52940-834d-11e7-8f4f-80a576260fa6.png" width=250>

However, with `detailed=True`, you'll get

<img src="https://user-images.githubusercontent.com/4609749/29409848-53f9e260-834e-11e7-9e82-d7ba573d38b0.png" width=250>

Would you have any recommendation for a layout that includes costs and word probabilities, but avoids `shape=record` in the dot specification?

**Comment by laeubli** [comment]
Turns out `record` nodes can be replaced using [HTML-like nodes](http://www.graphviz.org/doc/info/shapes.html#html), so non-ASCII characters should be visualised properly now.

<img width="250" src="https://user-images.githubusercontent.com/4609749/29411769-810c2b48-8356-11e7-989b-9446f19600ec.png">
