### ISSUE TITLE
ValueError: Parent directory of model doesn't exist, can't save.

### ISSUE THREAD

**Issue by jigyasa06** [EdinburghNLP/nematus#74]
INFO: Validation loss (AVG/SUM/N_SENT): 212.140906401 93129.8579102 439
2018-06-30 02:08:31.421233: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at save_restore_v2_ops.cc:109 : Not found: ; No such file or directory
Traceback (most recent call last):
  File "nematus/nmt.py", line 692, in <module>
    train(config, sess)
  File "nematus/nmt.py", line 313, in train
    saver.save(sess, save_path=config.saveto)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1720, in save
    raise exc
ValueError: Parent directory of model doesn't exist, can't save.

Can you please tell me why i am getting this error when i am running the nematus model for code generation task?

**Comment by rsennrich** [comment]
can you double-check your "--model" or "--saveto" argument, and make 
sure it points to a valid location in your file system?

best wishes,
Rico

**Comment by rsennrich** [comment]
Not sure where you get crashes. The size of the dataset only matters if you're short on disk space, or for shuffling (which you can do offline and disable in Nematus). Most memory problems are related to network or vocabulary size.Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [EdinburghNLP/nematus] ValueError: Parent directory of model doesn't exist, can't save. (#74)From: jigyasa06 To: EdinburghNLP/nematus CC: Rico Sennrich ,Comment Thank you so much for your reply .
I have one more doubt regarding the dataset for code generation.
Is there any automated way to reduce the dataset or I have to do it manually because the system on which I am running the model , is not that much powerful and I am getting segmentation faults again and again.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/EdinburghNLP/nematus","title":"EdinburghNLP/nematus","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/EdinburghNLP/nematus"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jigyasa06 in #74: Thank you so much for your reply .\r\nI have one more doubt regarding the dataset for code generation.\r\nIs there any automated way to reduce the dataset or I have to do it manually because the system on which I am running the model , is not that much powerful and I am getting segmentation faults again and again."}],"action":{"name":"View Issue","url":"https://github.com/EdinburghNLP/nematus/issues/74#issuecomment-401892629"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EdinburghNLP/nematus/issues/74#issuecomment-401892629",
"url": "https://github.com/EdinburghNLP/nematus/issues/74#issuecomment-401892629",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [EdinburghNLP/nematus] ValueError: Parent directory of model doesn't exist, can't save. (#74)",
"sections": [
{
"text": "",
"activityTitle": "**jigyasa06**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jigyasa06",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"EdinburghNLP/nematus\",\n\"issueId\": 74,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"EdinburghNLP/nematus\",\n\"issueId\": 74\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/EdinburghNLP/nematus/issues/74#issuecomment-401892629"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 352044156\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jigyasa06** [comment]
okay thank you so much i will look into it and will let you know. :)
