### ISSUE TITLE
Different result after converting model from Theano to TF

### ISSUE THREAD

**Issue by raymondhs** [EdinburghNLP/nematus#82]
Hi, I am experimenting with the pre-trained Nematus models for WMT'17, zh-en language pair.

I converted the pre-trained model to Tensorflow using this command: `python nematus/theano_tf_convert.py  --from_theano --in ../wmt17_systems/zh-en/model.l2r.ens1.npz --out ../wmt17_systems/zh-en/model-tf.l2r.ens1.npz`.

And run a single model translation using this command:
```
$model_dir/preprocess.sh | \
CUDA_VISIBLE_DEVICES=0 python $nematus_tf_home/nematus/translate.py \
      -m $model_dir/model-tf.l2r.ens1.npz \
      -k 12 -n -p 1  | \
$model_dir/postprocess.sh
```

I observed quite significant drop in BLEU:

Theano version:
`BLEU = 22.84, 56.7/29.1/17.0/10.4 (BP=0.982, ratio=0.982, hyp_len=52856, ref_len=53827)`

Tensorflow version:
`BLEU = 21.26, 53.8/26.8/15.4/9.2 (BP=1.000, ratio=1.044, hyp_len=56182, ref_len=53827)`

By the way, when I run the conversion code, the following was printed:
```
Not saving decoder_c_tt because no TF equivalent
The following TF variables were not assigned (excluding Adam vars):
You should see only 'beta1_power', 'beta2_power' and 'time' variable listed
time:0
beta1_power:0
beta2_power:0
```

I also noticed that `--suppress-unk` is no longer available when calling `translate.py`. Anything I've missed here? thanks :)

**Comment by pjwilliams** [comment]
Hi, thanks for the detailed report! I'll take a look at what's changed in the TensorFlow model recently to see if it's accidentally diverged. The line about decoder_c_tt looks suspicious but I don't think that's the problem since that parameter has never been mapped in the conversion (though I'll double check). I'll let you know what I find. In the meantime, I would recommend training TensorFlow models from scratch if you have that option.

Best wishes,
Phil
