### ISSUE TITLE
Improve translate.py logging

### ISSUE THREAD

**Issue by okgrammer** [EdinburghNLP/nematus#84]
Hello, I'm using Nematus to translate ~10M sentences. After running `translate.py` for a few hours, I saw that the the log doesn't show anything (e.g. the number translated so far) and my translation output file is still empty. I've tried this on a small subset of the data. Logs are only printed at the end (i.e. there are many lines of`INFO: Translated xxxx sents` only at the end). I am just thinking that it will be better if we can see how many sentence have been translated so far when the process is running.

**Comment by pjwilliams** [comment]
I've added a script called translate-2.py to a branch of the same name. It should work more or less as a drop-in replacement for translate.py but with the difference that it will write translations as it produces them (or after
a short delay). One difference that may or may not be important to you is that it ignores the --normalization_alpha parameter and uses the normalization settings from the model config file. Note that this script hasn't been thoroughly tested, so you may want to check that the output for a small subset of your input (e.g. 1000 sentences) matches the original translate.py before you spend too much GPU time on translating.

Best wishes,
Phil

**Comment by pjwilliams** [comment]
If you're not doing it already, you should use the -b option to set the batch size to the largest value that your GPU can handle (you'll need to experiment to find the point at which you get out of memory errors).

Nematus won't use multiple GPUs (though that should change in the near future), so to make use of more than one GPU you have to split the data yourself and run a separate instance on each GPU. The -p option internally runs multiple processes, each with a full copy of the model, though they are all run on the same GPU. This isn't particularly helpful for translate.py (where you can just increase the batch size instead) but it makes more sense for server.py, which shares the code.

Re Marian, I think it supports deep transition but not deep stacked models, although I'm not 100% sure. Did you convert the Nematus model from TensorFlow to Theano first? Marian is probably expecting a Theano model, so that might explain why it threw an error (rather than report that it's incompatible and exit gracefully).

Phil

**Comment by pjwilliams** [comment]
The stacked models in section 2.3 of Antonio's deep architectures paper: http://aclweb.org/anthology/W17-4710 <http://aclweb.org/anthology/W17-4710> ("deep stacked" isn't a further variation - we should have just said "stacked")

Phil

**Comment by emjotde** [comment]
OK. I think we do not have stacked cGRU and crGRU, other than that stacked architecture are supported (one cGRU at the bottom, others are GRU). Not sure about full compatibility with Nematus, some of them work. Might be that others need to be trained with Marian. @snukky ?

**Comment by okgrammer** [comment]
@pjwilliams Yup currently that's what I did -- split my data manually and run in 2 GPUs in parallel.
I think the error is similar to this: https://github.com/marian-nmt/marian/issues/138. In particular this line: `Graph was reloaded and parameter 'F0::encoder_bi_l2_cell1_U' is newly created`.

**Comment by snukky** [comment]
True, not all models trained with Nematus are supported by Marian. I needed to decode WMT17 models like this one: http://data.statmt.org/wmt17_systems/en-de/model.l2r.ens1.npz.json and didn't bother to have full compatibility. We had informative abort messages once.

**Comment by emjotde** [comment]
Roman mentioned that TF Nematus is not back-compatible with Theano Nematus. That would mean that the Marian models are not compatible with the current toolkit. If this is true, we should probably consider dropping those.

**Comment by pjwilliams** [comment]
TF Nematus can't load or generate Theano models directly, but there is a conversion script (theano_tf_convert.py) that can convert models between the two formats.

Phil
